spring.application.name=translator

spring.datasource.url=jdbc:postgresql://localhost:5432/translator_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

groq.api.url=${URL_GROQ}
groq.api.key=${API_GROQ}
groq.base.url=${BASE_URL_GROQ}
groq.model=${MODEL_GROQ}


jwt.secret-key=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

notification.api=${NOTIFICATION_API}
notification.url=${NOTIFICATION_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
