spring.application.name=translator

spring.datasource.url=jdbc:postgresql://localhost:5432/translator_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/translator_docs?authSource=admin

groq.api.url=${URL_GROQ}
groq.api.key=${API_GROQ}
groq.model=${MODEL_GROQ}